name: Python CI + Jenkins Trigger

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python App using Secret
        env:
          NAME: ${{ secrets.NAME }}  
        run: python app.py

      - name: Run Python App using environment variable
        env:
          NAME: ${{ vars.NAME }}
        run: python app.py

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://54.252.239.31:8080/job/python-job/buildWithParameters?token=mytoken123&BRANCH_NAME=main&ENVIRONMENT=dev&RUN_TESTS=true" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"